### PR TITLE
API: Add unit tests

### LINKED ISSUE #99: API service: add tests
### What is the expected enhancement?

Add endpoint tests for API service. 

Ref: https://www.django-rest-framework.org/api-guide/testing/#api-test-cases

Required to address JoSS review comments https://github.com/openjournals/joss-reviews/issues/5673#issuecomment-1679076266

### PR DESCRIPTION
**Pull request by mickahell**
### Summary
Add unit tests for the API and make them autom with Actions.

### Details and comments
- [x] Create django unit tests
- [x] Updated doc + readme on details
- [x] Add unit test launching into Docker.dev
- [x] Add django env into tox
- [x] Add coverage report
- [x] Launching django tests from CI

---
Closes #99

### CODE REVIEW

**Comment by mickahell** [comment]
@IceKhan13 @AnsahMohammad ready for your review :)

**Comment by IceKhan13** [comment]
sweet! let's CI pass checks and we are good to go!

**Comment by IceKhan13** [comment]
BTW this is PR 100!

**Comment by mickahell** [comment]
> BTW this is PR 100!

Yeaaaaah 🥳 🎉

**Comment by mickahell** [comment]
> sweet! let's CI pass checks and we are good to go!

🏁

**Review by IceKhan13 — APPROVED** [review]

**Pull request merged**
