### PR TITLE
Client: Split trial.json into diff files

### LINKED ISSUE #122: Client: Split trial.json into different files
### What is the expected enhancement?

In order to avoid having a **HUGE** file, we need to split the different element of the trial.json file into different files.

```bash
/path
- /trial_<uuid>
-- /trial.json # trial name, id, tags, description, etc
-- /circuit_1.json # circuit 1
-- /circuit_2.json # circuit 2
-- /circuit_3.json # circuit 3
-- /text_1.json # text 1
```

### PR DESCRIPTION
**Pull request by mickahell**
### Summary

Export circuits and texts from trial json into diff files.
Details about folder organization : #122 

### Details and comments

- [x] Reorganize into `trial_uuid` folders
- [x] Simply to have any get using the `get()` function and any save to use the `save()` function
- [x] Export circuits
- [x] Export texts
- [x] Update unit tests

---
Closes #122

### CODE REVIEW

**Comment by mickahell** [comment]
@IceKhan13 @AnsahMohammad 
I'm pretty sure it has a better way to encode and decode external part of trial.json (maybe even adding a ref from trial.json to go read external file so then encoding and decoding can be done only once for all).

**Comment by IceKhan13** [comment]
@mickahell put this PR as ready for review when you are done :) 

Thank you! Already looks good :)

**Comment by mickahell** [comment]
@IceKhan13 @AnsahMohammad ready for your review :)

**Review by IceKhan13 — APPROVED** [review]
Let's go! 🚀

**Pull request merged**
